import { PostListItem } from '@/types/apis/community'

export const dummyCommunityPosts: PostListItem[] = [
  {
    id: 1,
    title: '첫 번째 게시글',
    content: '오늘 날씨가 정말 좋네요!',
    category: '일상',
    author: { userId: 'hong', name: '홍길동' },
    tags: ['일상'],
    viewCount: 123,
    likeCount: 10,
    commentCount: 2,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'React 공부중',
    content: 'React 18의 새로운 기능들을 정리했습니다.',
    category: '프론트엔드',
    author: { userId: 'lee', name: '이순신' },
    tags: ['React', '공부'],
    viewCount: 456,
    likeCount: 25,
    commentCount: 5,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'Next.js 질문',
    content: 'getServerSideProps와 getStaticProps 차이가 뭔가요?',
    category: '프론트엔드',
    author: { userId: 'kang', name: '강감찬' },
    tags: ['Next.js', '질문'],
    viewCount: 78,
    likeCount: 3,
    commentCount: 1,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    title: '취미 공유',
    content: '최근에 사진 찍는 취미를 시작했어요!',
    category: '취미',
    author: { userId: 'yu', name: '유관순' },
    tags: ['사진', '취미'],
    viewCount: 200,
    likeCount: 15,
    commentCount: 3,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    title: '코딩 챌린지',
    content: '오늘 100일 코딩 챌린지 50일차 달성!',
    category: '코딩',
    author: { userId: 'jeong', name: '정약용' },
    tags: ['코딩', '챌린지'],
    viewCount: 150,
    likeCount: 12,
    commentCount: 4,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    title: '운동 기록',
    content: '오늘은 5km 조깅 성공!',
    category: '운동',
    author: { userId: 'shin', name: '신사임당' },
    tags: ['운동', '조깅'],
    viewCount: 90,
    likeCount: 8,
    commentCount: 1,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    title: '책 추천',
    content: '‘자바스크립트 완벽 가이드’ 추천합니다.',
    category: '독서',
    author: { userId: 'kim', name: '김유신' },
    tags: ['책', '추천', 'JS'],
    viewCount: 300,
    likeCount: 22,
    commentCount: 6,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    title: '맛집 후기',
    content: '최근에 간 카페가 정말 분위기 좋았어요.',
    category: '일상',
    author: { userId: 'jang', name: '장영실' },
    tags: ['카페', '맛집'],
    viewCount: 180,
    likeCount: 14,
    commentCount: 2,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 9,
    title: '여행 계획',
    content: '다음 달 제주도로 여행 갈 계획이에요.',
    category: '여행',
    author: { userId: 'sejong', name: '세종대왕' },
    tags: ['여행', '제주도'],
    viewCount: 220,
    likeCount: 18,
    commentCount: 5,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 10,
    title: '스터디 모집',
    content: 'React 스터디 참여하실 분 구합니다.',
    category: '스터디',
    author: { userId: 'hwang', name: '황희' },
    tags: ['React', '스터디'],
    viewCount: 140,
    likeCount: 10,
    commentCount: 3,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    title: '스터디 모집',
    content: 'React 스터디 참여하실 분 구합니다.',
    category: '스터디',
    author: { userId: 'hwang', name: '황희' },
    tags: ['React', '스터디'],
    viewCount: 145,
    likeCount: 11,
    commentCount: 2,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 12,
    title: '스터디 모집',
    content: 'React 스터디 참여하실 분 구합니다.',
    category: '스터디',
    author: { userId: 'hwang', name: '황희' },
    tags: ['React', '스터디'],
    viewCount: 150,
    likeCount: 12,
    commentCount: 4,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 13,
    title: '스터디 모집',
    content: 'React 스터디 참여하실 분 구합니다.',
    category: '스터디',
    author: { userId: 'hwang', name: '황희' },
    tags: ['React', '스터디'],
    viewCount: 155,
    likeCount: 13,
    commentCount: 3,
    isAnonymous: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 14,
    title: '스터디 모집',
    content: 'React 스터디 참여하실 분 구합니다.',
    category: '스터디',
    author: { userId: 'hwang', name: '황희' },
    tags: ['React', '스터디'],
    viewCount: 160,
    likeCount: 14,
    commentCount: 5,
    isAnonymous: false,
    createdAt: '2025-08-18T10:30:00.000Z', // 2025년 8월 18일 오전 10시 30분
  },
  {
    id: 15,
    title: '스터디 모집',
    content: 'React 스터디 참여하실 분 구합니다.',
    category: '스터디',
    author: { userId: 'hwang', name: '황희' },
    tags: ['React', '스터디'],
    viewCount: 165,
    likeCount: 15,
    commentCount: 4,
    isAnonymous: false,
    createdAt: '2025-08-17T15:45:00.000Z', // 2025년 8월 17일 오후 3시 45분
  },
]
